### ISSUE TITLE
Tópico <03>

### ISSUE THREAD

**Issue by thiagows** [plinioleitao/bes-bd-2020-2#101]
**1.**

Ponto 1: Não está claro se um projeto pode ser gerenciado por mais de um funcionário ou apenas um.
Ponto 2: Não está claro se já uma quantidade máxima de projetos por funcionário.
Ponto 3: Não está claro se há um limite de supervisores por funcionário.
Ponto 4: Não está claro se existe um limite de projetos por departamento.
Ponto 5: Não está claro se o funcionário que gerencia do departamento pode ser supervisionado.

**2.**
Não.

**Comment by plinioleitao** [comment]
COM APROVEITAMENTO.
