### ISSUE TITLE
Tópico <06>

### ISSUE THREAD

**Issue by isabia** [plinioleitao/bes-bd-2020-2#112]
- compartilhamento de dados entre múltiplos usuários: 
      Com o SGBD é possível que diversos usuários acessem a mesma base de dados, de modo que todos acessem essa base com seu próprio usuário.
Ex: banco de dados local de uma empresa
- restrição de acesso aos dados para usuários não autorizados
	No SGBD é possível restringir o acesso de algumas funcionalidades e de     acesso ao banco de dados mesmo. 
	Ex: no meu trabalho tenho apenas permissão de leitura no banco de dados de produção com meu usuário

**Comment by plinioleitao** [comment]
Sugiro refletir mais sobre o primeiro ponto.
COM APROVEITAMENTO.
