### ISSUE TITLE
Abertura de tópicos 

### ISSUE THREAD

**Issue by vanessabrenda** [plinioleitao/bes-bd-2020-2#180]
Por algum motivo foi redirecionado para o portal errado, coisa que aconteceu apenas nas duas últimos atividades identificando claramente um erro, uma confusão, onde foi postado DENTRO do prazo, então tirei um tempo do serviço para ajustar para o portal correto e agora eu perco as duas atividades? 
Eu vi que já havia passado do prazo, está explícito. 
Mas parecia possível o tratamento de excessão já que foram as primeiras atividades da matéria e foram feitas no prazo.

**Comment by plinioleitao** [comment]
Vamos solucionar da melhor forma possível, seu caso não é o único.
No próximo encontro síncrono, 08/03/2021, falaremos sobre isso, na direção de alcançar uma solução e, principalmente, evitar que possa ocorrer novamente.
