### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by robertaassis** [plinioleitao/bes-bd-2020-2#186]
Professor, referente ao tópico 08, estava analisando outros diagramas a parte pra entender a relação entre eles e fiquei em dúvida se nas perguntas 4 e 5, quando o senhor diz "a pelo menos uma agência" engloba também ser somente uma agência? Pois como o relacionamento é 1.n, no caso só poderia ser uma.

**Comment by plinioleitao** [comment]
Ao postar uma dúvida, favor usar o título "[Dúvida] <escreva aqui o assunto da sua dúvida>".
O trecho "... pelo menos uma agência" significa uma ou mais agências.
