### ISSUE TITLE
tópico 05

### ISSUE THREAD

**Issue by Webse-Costa** [plinioleitao/bes-bd-2020-2#295]
1-	Sendo a definição mais sintética para metadados “Dados sobre dados”  e apresentando as principais diferenças entre processamento de arquivos tradicional e abordagem de banco de dados: Natureza de autodescrição de um sistema de banco de dados.  Isolamento entre programas e dados, e abstração de dados. Suporte de múltiplas visões dos dados. Compartilhamento de dados e processamento de transação multiusuário o local dos metadados é no catálogo do SGBD, pois remete a ideia de dados sobre dados. 
2-	A consequência/impacto  será as alterações nos relatórios com base nos metadados inseridos e/ou removidos e/ou aglutinados.

**Comment by plinioleitao** [comment]
A primeira questão solicita "o local dos metadados" em cada estratégia.
A segunda questão solicita "para cada estratégia qual o impacto devido ao local dos metadados, **quando metadados precisam ser modificados**".
É preciso responder objetivamente cada questão.
SEM APROVEITAMENTO.
