### ISSUE TITLE
"Tópico 02

### ISSUE THREAD

**Issue by KasTs** [plinioleitao/bes-bd-2020-2#53]
**1-R:**
Banco de dados é um conjunto de informaçoes (dados), organizados para facil acesso para consultas, modificações e adicionar informacoes.
**2-R:**  
**Durabilidade:** Significa que os efeitos de uma transação são permanentes, podendo ser desfeitos somente como resultado de uma transação posterior e bem-sucedida.
**Esquema de banco de dados:** refere-se a uma representação visual de um banco de dados, um conjunto de regras que governa um banco de dados ou todo o conjunto de objetos pertencentes a um determinado usuário.
**linguagem de consulta:** é uma linguagem de computador usada para realizar consultas em bancos de dados, por exemplo SQL, que da pra fazer manipular o tipos de consultas que irá fazer ao banco.

**Comment by plinioleitao** [comment]
O "Esquema de banco de dados" pode ter ou não uma representação visual, tal como um diagrama.
COM APROVEITAMENTO.
