### ISSUE TITLE
[Dúvida] Relacionado ao tópico 20 

### ISSUE THREAD

**Issue by flavimarsilva** [plinioleitao/bes-bd-2020-2#693]
Eu estava fazendo o tópico 20 e queria usar a operação divisão mas quando fui tentar não consegui fazer por não visualizar muito bem a logica da operação

você poderia me explicar melhor como funciona a operação divisão?

desde já agradeço.

**Comment by plinioleitao** [comment]
Flavimar,

DIVISÃO é uma operação binária, T ← R ÷ S, cujo resultado T é uma relação que conterá apenas os elementos de R que se relacionam com todos os elementos de S.

Especificamente, veja a [figura](https://github.com/plinioleitao/bes-bd-2020-2/blob/master/media/fig-algebra-divisao.jpg), em que a Relação T seleciona os valores em R que estão para todos os valores de S.
