### ISSUE TITLE
[Dúvida] - Tópico 21

### ISSUE THREAD

**Issue by isabia** [plinioleitao/bes-bd-2020-2#745]
As demandas informacionais introduzidas em Reflexões 04 no Tópico 18 (acima) foram solucionadas pelo DER abaixo.

![image](https://user-images.githubusercontent.com/38692064/115972080-c6efaf80-a522-11eb-9313-6a1881fe096e.png)

Favor apreciar novas reflexões para o BD Venda Online:
Reflexões 05 - Que alterações no esquema conceitual (DER) atendem às seguintes consultas:

Quais o valor total das parcelas pagas e o valor total das parcelas não pagas de uma venda?
Quais as parcelas pagas em atraso?
Quais os juros cobrados nas parcelas pagas em atraso?

- **Sobre esta questão, se eu adicionar um atributo de data_vencimento à parcela é suficiente para essas demandas informacionais?**

**Comment by plinioleitao** [comment]
Eu penso que é necessário acrescentar dois atributos em PARCELA:
- Data de Vencimento
- Valor dos juros
