### ISSUE TITLE
Duvida Tópico 12

### ISSUE THREAD

**Issue by CMedrado** [plinioleitao/bes-bd-2020-2#808]
Estava olhando minhas atividades com aproveitamento e a do tópico 12 se encontra vazia.

Gostaria de entender oque eu errei nela.

Matricula: 201801533

**Comment by plinioleitao** [comment]
Oi Rafael, no GitHub não consta qualquer _issue_, de sua autoria, com o título "Tópico 12". Ou seja, a atividade do Tópico 12 não foi respondida.

**Comment by CMedrado** [comment]
Olhei aqui e realmente havia colocado no lugar errado, peço desculpa, mas se tiver como dar uma olhada para ver os erros sem considera-lo ficaria grato.
https://github.com/CMedrado/bes-bd-2020-3/blob/master/topicos/topico-12.jpeg
