### ISSUE TITLE
[Dúvida] Dúvida sobre o Tópico 24 

### ISSUE THREAD

**Issue by RandersonF** [plinioleitao/bes-bd-2020-2#829]
Professor, no tópico 24 foi questionado se alguém poderia se voluntariar a criar uma nova versão do arquivo disposto tratando os dados do BD Empresa, mas pelo que vi, o próprio arquivo disponibilizado (https://github.com/plinioleitao/bes-bd-2020-2/blob/master/data/empresa.sql) já faz essa tratativa.

Já foi feito por outro aluno? O Sr. atualizou? Entendi mal a solicitação?

**Comment by plinioleitao** [comment]
Oi Randerson, sim já foi feito por outro aluno, obrigado por perguntar.
