### ISSUE TITLE
[Dúvida] Tópico 25 questão 1 

### ISSUE THREAD

**Issue by isabia** [plinioleitao/bes-bd-2020-2#879]
Em consultas escritas em SQL, quando há pelo menos um NULL no predicado da cláusula WHERE, o resultado da avaliação é "desconhecido" (exceto quando são explicitamente empregados IS NULL ou IS NOT NULL); por exemplo, o resultado da avaliação de (3 + NULL > 7) é "desconhecido". Portanto, "verdadeiro", "falso" e "desconhecido" são os resultados possíveis na avaliação de predicados da cláusula WHERE. A regra geral é que são selecionadas apenas as combinações de tuplas em que o predicado é avaliado como “verdadeiro”. Seja a relação R que possui quatro tuplas – (12, 15, 5100), (13, NULL, 3500), (14, NULL, NULL) e (15, 12, NULL) – em que o primeiro, o segundo e o terceiro valores em cada tupla referem-se aos atributos at1, at2 e at3, respectivamente. Os comandos a seguir representam consultas sobre R:
    (C1) SELECT * FROM R WHERE (at1>=12) AND (at2>14)
    (C2) SELECT * FROM R WHERE (at2>12) OR (at3>3000)
    (C3) SELECT * FROM R WHERE (NOT (at1<at2))
A quantidade de tuplas retornadas pelas execuções dos comandos (C1), (C2) e (C3), respectivamente, é:
  (a) dois, um e dois.
  (b) dois, dois e um.
  (c) dois, dois, dois.
  (d) um, um e dois.
  (e) um, dois e um.

Professor, nesta questão eu fiz e encontrei o resultado um, um, um. Mas ele não está entre as opções, segue a minha lógica para resolução:

at1    at2   at3
(12, 15, 5100),
(13, NULL, 3500), 
(14, NULL, NULL) 
(15, 12, NULL) 

(C1) SELECT * FROM R WHERE (at1>=12) AND (at2>14) 1
(12, 15, 5100)

(C2) SELECT * FROM R WHERE (at2>12) OR (at3>3000) 1
(12, 15, 5100),

(C3) SELECT * FROM R WHERE (NOT (at1<at2)) 1
(15, 12, NULL) 
 
r: um, um, um

O que eu errei neste caso?

**Comment by plinioleitao** [comment]
Sobre os predicados de seleção:
■ (at1>=12) AND (at2>14)
■ (at2>12) OR (at3>3000)
■ (NOT (at1<at2))
Quando os atributos **at1**, **at2** e/ou **at3** possuem valor nulo, a condição (por exemplo '(at1>=12)') é avaliada como "desconhecida" (ou seja, "falsa").

**Comment by IanChaves** [comment]
Professor, com esta explicação de que "desconhecido" entende-se como falso, a resposta encontrada então seria (um, um, três) não tem entre as alternativas também... estou deixando passar alguma coisa?

**Comment by plinioleitao** [comment]
Veja o enunciado:
- " _Portanto, “verdadeiro”, “falso” e “desconhecido” são os resultados possíveis na avaliação de predicados da cláusula WHERE. A regra geral é que são selecionadas apenas as combinações de tuplas em que o predicado é avaliado como “verdadeiro”_ ".
- Por isso que "desconhecido" entende-se como "falso".

Então, estejam atentos à aplicação dos operadores OR, AND e NOT.
